### ISSUE TITLE
Feature Request: Set mods you want to be notified for

### ISSUE THREAD

**Issue by Ismoh** [SpeckledFleebeedoo/Factorio-mod-notifier#2]
I installed/added the bot to my server to get notified, if one or more specific mod was updated, because I am only interested in some of the mods.

In addition to this, it would be awesome to get notifications when any reply on mods portal 'forum' was created.

Thanks a lot!

If anything is unclear, give me a shout!
Have a good one!

**Comment by SpeckledFleebeedoo** [comment]
I have the mod filtering working on my unstable branch. Unfortunately there are still some bugs surrounding the discord python library, so this will probably be released once that goes stable.

As for discussion notifications: there is no api for these, so I have no good way of implementing that. There is a subscribe button in the mod portal itself though, which will give you email notifications for new threads.

**Comment by Ismoh** [comment]
Thanks for the reply and suggestion!

**Comment by SpeckledFleebeedoo** [comment]
I've pushed out an update including both slash commands as well as whitelist filter on the mod notifications. Should be fairly self-explanatory :)

**Comment by Ismoh** [comment]
Could you be so kind to provide me the bots invite ulr again?

**Comment by SpeckledFleebeedoo** [comment]
Solved on discord

**Comment by Ismoh** [comment]
![image](https://user-images.githubusercontent.com/12631485/168082726-cf6e1981-e112-48c1-99ea-dcfc2aa8c544.png)

Just for history and consistency
